version: '3.8'

services:

  gateway:
    container_name: api-gateway
    hostname: api-gateway
    build: ./api-gateway
    image: slimane2/challenge-api-geteway
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - my-network
    command: sh -c "npm install && npm run start:dev"
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin_password
        - RABBITMQ_USER=admin
        - RABBITMQ_PASS=admin_password
        - RABBITMQ_HOST=localhost:5672
        - RABBITMQ_AUTH_QUEUE=auth_queue
        - JWT_SECRET=JWT_ACCESS_SECRET
        - RABBITMQ_URL=amqp://admin:admin_password@rabbitmq:5672
        - INSURANCE_SERVICE_QUEUE=insurance_service_queue
        - USER_SERVICE_QUEUE=user_service_queue
        - QUOTE_SERVICE_QUEUE=quote_service_queue
        - API_GATEWAY_QUEUE=api_gateway_queue
        - JWT_ACCESS_SECRET=JWT_ACCESS_SECRET
        - JWT_REFRESH_SECRET=bKGR7ScxSnX/U76cu62/pUElk71DSiZTjGS/yyCokgsUvbT8nG6Xnv88M2Ya1mz58WNPdiy4sODJrAWA40zOPq08G+UdtPf6YtownNRxruZM2+toXopCVEEa3/7+FyDPlx28aP/yLm5jG610fYVprY8ZMNkbbQZtIOUINwAjvgWPfd30I6qsWtRJleuKcCay2ndM54LEZKXH9XbegsZ9TWeITkbSbKMVG4G2Tjnakr+qFmlnAM8eLpwSxiezRIKZtjTFNP9mIoTzJhlePCNlReIvUxczIcy1eY1K5Si1qXgOYGizlZrZ2NzyXYdmwK7ZCEFnt9iIAHLlklkq8XfiSw==

  webserver:
      build:
        context: ./nginx
      image: slimane2/challenge-webserver
      container_name: nginx
      hostname: nginx
      ports:
        - 80:80
        - 443:443
      depends_on:
        - gateway
      networks:
        - my-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin_password
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  insurancedatabase:
    container_name: insurancedatabase
    image: mongo:latest
    hostname: insurancedatabase
    volumes:
      - ./insurance-service/data/db:/data/db
    ports:
      - "27018:27017"
    networks:
      - my-network

  insurance-api:
    container_name: insurance-api
    build: ./insurance-service
    image: slimane2/challenge-insurence-service
    volumes:
      - ./insurance-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    depends_on:
      - insurancedatabase
      - gateway
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://insurancedatabase:27017/nestjs-mongodb
      - RABBITMQ_URL=amqp://admin:admin_password@rabbitmq:5672
      - INSURANCE_SERVICE_QUEUE=insurance_service_queue
      - QUOTE_SERVICE_QUEUE=quote_service_queue
    networks:
      - my-network

  quote-service:
    container_name: quote-api
    build: ./quote-service
    image: slimane2/challenge-quote-service
    ports:
      - '3002:3002'
    depends_on:
      - quotedatabase
      - gateway
      - rabbitmq
    volumes:
      - ./quote-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgres://user:password@quotedatabase:5432/nestjsdb
      - INSURANCE_SERVICE_QUEUE=insurance_service_queue
      - RABBITMQ_URL=amqp://admin:admin_password@rabbitmq:5672
      - QUOTE_SERVICE_QUEUE=quote_service_queue
    networks:
      - my-network

  quotedatabase:
    container_name: quotedatabase
    image: postgres:13
    hostname: quotedatabase
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjsdb
    ports:
      - '5432:5432'
    volumes:
      - ./quote-service/data/db:/var/lib/postgresql/data
    networks:
      - my-network


  user-database:
    container_name: user-database
    hostname: user-database
    image: mongo:latest
    volumes:
      - ./user/data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

  user-service:
    container_name: user-service
    hostname: user-service
    build: ./user
    image: slimane2/challenge-user
    volumes:
      - ./user:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3004:3004
    depends_on:
      - user-database
      - gateway
      - rabbitmq
    environment:
      - APP_PORT=3000
      - MONGODB_URL=mongodb://user-database:27017/db
      - JWT_SECRET=JWT_ACCESS_SECRET
      - JWT_EXPIRATION_TIME=3600s
      - REFRESH_TOKEN_SECRET=SECRET
      - REFRESH_TOKEN_EXPIRATION_TIME=604800s
      - JWT_ACCESS_SECRET=JWT_ACCESS_SECRET
      - JWT_REFRESH_SECRET=JWT_ACCESS_SECRET
    networks:
      - my-network

  utils-service:
    container_name: utils-service
    hostname: utils-service
    build: ./utils
    image: slimane2/challenge-utils
    volumes:
      - ./utils:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3005:3005
    depends_on:
      - utils-database
      - gateway
      - rabbitmq
    environment:
      - APP_PORT=3005
      - MONGODB_URL=mongodb://utils-database:27017/db
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_USER=03zaki95@gmail.com
      - MAIL_PASSWORD=zaki1998
      - MAIL_FROM=Azulance App<03zaki95@gmail.com>
      - SEND_IN_BLUE_API_KEY=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
      - CLIENT_URL=https://magenta-speculoos-e4c9ef.netlify.app/
    networks:
      - my-network
  utils-database:
    container_name: utils-database
    hostname: utils-database
    image: mongo:latest
    volumes:
      - ./utils/data/db:/data/db
    ports:
      - "27020:27017"
    networks:
      - my-network

  claims-database:
    container_name: claims-database
    image: mongo:latest
    hostname: claims-database
    volumes:
      - ./claims/data/db:/data/db
    ports:
      - "27021:27017"
    networks:
      - my-network

  claims-service:
    container_name: claims-service
    hostname: claims-service
    build: ./claims
    image: slimane2/challenge-claims
    volumes:
      - ./claims:/src/app
      - /src/app/node_modules
    ports:
      - 3006:3006
    depends_on:
      - claims-database
      - gateway
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://claims-database:27017/db
    networks:
      - my-network

  payment-database:
    container_name: payment-database
    image: mongo:latest
    hostname: payment-database
    volumes:
      - ./payment/data/db:/data/db
    ports:
      - "27022:27017"
    networks:
      - my-network

  payment-service:
    container_name: payment-service
    hostname: payment-service
    build: ./payment
    image: slimane2/challenge-payment
    volumes:
      - ./payment:/src/app
      - /src/app/node_modules
    ports:
      - 3007:3007
    depends_on:
      - payment-database
      - gateway
      - rabbitmq
    environment:
      - MONGODB_URL=mongodb://payment-database:27017/db
      - RABBITMQ_URL=amqp://admin:admin_password@rabbitmq:5672
      - INSURANCE_SERVICE_QUEUE=insurance_service_queue
      - QUOTE_SERVICE_QUEUE=quote_service_queue
      - STRIPE_SECRET_KEY=sk_test_51MZYljHiiKajDgAsM1cjE9n1V1LNfO2jrHRyo3Hox5yGRvNJo7ctXlarwUEx1CP8IHM2GiNJm95HdKxr3CSncaUX00sg1WxEQu
      - STRIPE_CURRENCY=eur
      - CLIENT_URL=https://magenta-speculoos-e4c9ef.netlify.app
    networks:
      - my-network

  kpi-database:
    container_name: kpi-database
    image: mongo:latest
    hostname: kpi-database
    volumes:
      - ./kpi/data/db:/data/db
    ports:
      - "27023:27017"
    networks:
      - my-network

  kpi-service:
    container_name: kpi-service
    hostname: kpi-service
    build: ./kpi
    image: slimane2/challenge-kpi
    volumes:
      - ./kpi:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3008:3008
    depends_on:
      - kpi-database
      - gateway
      - rabbitmq
    environment:
      - MONGODB_URL=mongodb://kpi-database:27017/db
      - RABBITMQ_URL='amqp://admin:admin_password@rabbitmq:5672'
    networks:
      - my-network
networks:
  my-network:
    
