version: '3.8'

services:
  database:
    container_name: database
    image: mongo:latest
    hostname: database
    volumes:
      - ./kpi/data/db:/data/db
    env_file:
      - ./kpi/.env
    ports:
      - "27017:27017"
    networks:
      - my-network

  kpi-service:
    container_name: kpi-service
    hostname: kpi-service
    build: ./kpi
    volumes:
      - ./kpi:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file:
      - ./kpi/.env
    networks:
      - my-network
networks:
  my-network:
    
