name: Deploy

on:
  push:
    branches:
      - feature/cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH to DigitalOcean Server
        run: |
          ssh root@165.232.149.190 'docker stack deploy --compose-file docker-compose.yml challenge'
